### ISSUE TITLE
Not working with Updated IntelliJ version

### ISSUE THREAD

**Issue by indrajeet4192** [dev-tools-for-enterprise-java/mp-starter-intellij-ext#19]
I have updated Intellij IDE , then it is showing me below error.

**"Plugin error: Plugin 'MicroProfile Starter' (version '0.3.2') is not compatible with the current version of the IDE, because it requires build 203 or older but the current build is IC-203.5981.155".**

Kindly look into this

**Comment by moghaddam** [comment]
The new build with a fix for this issue is waiting Jetbrain's approval to get published. It should be available for download withing 2 business days.
