### ISSUE TITLE
IntelliJ plugin failed to fetch from MicroProfile Starter API

### ISSUE THREAD

**Issue by yeekangc** [dev-tools-for-enterprise-java/mp-starter-intellij-ext#22]
This was with IntelliJ IDEA (Community Edition) 2020.3.1.

<img width="1289" alt="Screen Shot 2021-01-19 at 7 42 52 AM" src="https://user-images.githubusercontent.com/4803104/105036346-5bc9a500-5a2a-11eb-852a-dfef6bbcbaf1.png">
<img width="1092" alt="Screen Shot 2021-01-19 at 7 43 03 AM" src="https://user-images.githubusercontent.com/4803104/105036349-5cfad200-5a2a-11eb-8054-35e7d60616a4.png">

Switching between JDKs didn't help.

FYI, @moghaddam @Emily-Jiang.

**Comment by moghaddam** [comment]
I'll take a look at it.

**Comment by yeekangc** [comment]
Thank you, @moghaddam!

**Comment by bhattacharyyasom** [comment]
This problem is still there. Is there a estimate on when this can be available. I am willing to help too.

**Comment by bhattacharyyasom** [comment]
Okay I am seeing a model attribute missing. The attribute is `specCodes`. Adding that addressed the problem.

**Comment by yeekangc** [comment]
@bhattacharyyasom submitted a PR here: https://github.com/MicroShed/mp-starter-intellij-ext/pull/23.  Thanks.

**Comment by moghaddam** [comment]
This is now fixed in the PR #23. The new version is published and will be available for download in a couple of days.
