### ISSUE TITLE
No builds compatible with IntelliJ IDEA 2021.2 and 2021.3

### ISSUE THREAD

**Issue by jreznot** [dev-tools-for-enterprise-java/mp-starter-intellij-ext#24]
Hi, seems plugin is not compatible with recent 2 major versions of IntelliJ IDEA

https://plugins.jetbrains.com/plugin/13386-microprofile-starter/versions

0.3.4 supports only 2020.1 — 2021.1.3 range

**Comment by kathrynkodama** [comment]
Encountered the same error with IntelliJ CE

```
Plugin error: Plugin 'MicroProfile Starter' (version '0.3.4') is not compatible with the current version of the IDE, because it 
requires build 211.* or older but the current build is IC-213.6777.52
```

**Comment by yeekangc** [comment]
We are looking to address this.  @moghaddam, are you available to refresh the marketplace entry?

**Comment by moghaddam** [comment]
Sure. I'll check it as soon as I get to my laptop 😉

**Comment by moghaddam** [comment]
@yeekangc I just created a PR for this #25

**Comment by moghaddam** [comment]
The updated version 0.3.5 is now approved by JetBrain Marketplace and is available for download.
