### ISSUE TITLE
Update the Intellij plug to use the latest MP Starter version 

### ISSUE THREAD

**Issue by Emily-Jiang** [dev-tools-for-enterprise-java/mp-starter-intellij-ext#26]
The latest MP starter supports MP 5.0. Can the vscode extension be updated to consume the latest version?
@moghaddam can you handle this?

**Comment by moghaddam** [comment]
Sure. I'll check it as soon as I can.

**Comment by Emily-Jiang** [comment]
Thank you @moghaddam

**Comment by moghaddam** [comment]
@Emily-Jiang I just found some time to work on this, but I couldn't find out what you expect me to do for MP 5.0. Is there any specific changes that I should consider? Because it's working already and shows MP 5.0 as an option too and I managed to create a sample project with it.

**Comment by Emily-Jiang** [comment]
ah, I thought you need to update the version of mp starter. If it works already, it is good then. Thank you @moghaddam for looking into this!

**Comment by Emily-Jiang** [comment]
close this issue as it works based on the info from @moghaddam
