### ISSUE TITLE
No builds compatible with latest IntelliJ version (2022.2)

### ISSUE THREAD

**Issue by themnexurst** [dev-tools-for-enterprise-java/mp-starter-intellij-ext#27]
Hi, seems plugin is not compatible with the recent major version (2022.*) of IntelliJ

Currently vesion 0.35 supports only up to 2021.1.3, while currently IntelliJ's most recent version is 2022.2.2
https://plugins.jetbrains.com/plugin/13386-microprofile-starter/versions

**Comment by kathrynkodama** [comment]
Any updates on resolving this issue? I am running into the same error:
<img width="723" alt="image" src="https://user-images.githubusercontent.com/26146482/206245486-7b6dcc4a-76d9-40fc-a431-2f686d68ab0f.png">

**Comment by moghaddam** [comment]
This got fixed last time. I forgot to close the issue. Now it's a new IntelliJ release and we should re-release again. I'll do it.

**Comment by kathrynkodama** [comment]
@moghaddam thank you!
